# Generated by Django 2.2.7 on 2019-12-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser', models.TextField(blank=True, db_column='Loser', null=True)),
                ('loserscore', models.IntegerField(blank=True, db_column='LoserScore', null=True)),
                ('winner', models.TextField(blank=True, db_column='Winner', null=True)),
                ('winnerscore', models.IntegerField(blank=True, db_column='WinnerScore', null=True)),
                ('topscorer', models.TextField(blank=True, db_column='TopScorer', null=True)),
                ('topscorerpoints', models.IntegerField(blank=True, db_column='TopScorerPoints', null=True)),
            ],
            options={
                'db_table': 'boxScore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playersinfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('player_id', models.TextField(blank=True, db_column='Player_id', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('position', models.TextField(blank=True, db_column='Position', null=True)),
                ('height', models.FloatField(blank=True, db_column='Height', null=True)),
                ('birthdate', models.TextField(blank=True, db_column='Birthdate', null=True)),
                ('college', models.TextField(blank=True, db_column='College', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
            ],
            options={
                'db_table': 'playersInfo',
                'managed': False,
            },
        ),
    ]
