# Generated by Django 3.0.7 on 2020-06-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debatestatus',
            name='username',
        ),
    ]
