# Generated by Django 3.0.4 on 2020-05-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_debate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'managed': False},
        ),
    ]
