# Generated by Django 3.0.4 on 2020-05-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200530_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='p1_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='p1_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='p2_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='p2_user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
