# Generated by Django 3.0.4 on 2020-05-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200531_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='user_pick',
            field=models.TextField(default='1'),
        ),
    ]
